export const INCUTWINS_LOADING        = 'INCUTWINS_LOADING';
export const INCUTWINS_SUCCESS        = 'INCUTWINS_SUCCESS';
export const INCUTWINS_FAILED         = 'INCUTWINS_FAILED';
export const INCUTWIN_REALTIME_UPDATE = 'INCUTWIN_REALTIME_UPDATE';
export const INCUTWIN_REMOVE          = 'INCUTWIN_REMOVE';
